# Credentials
OZON_API_URL = ""
# OZON_API_KEY = ""
OZON_API_KEY = ""
OZON_CLIENT_ID = ""

# Package dimensions, mm , g
MAX_LENGTH = 1790
MAX_DEPTH = 790
MAX_HEIGHT = 790
MAX_WEIGHT = 25000
CUSTOM_WEIGHT = 12000
MAX_PRODUCT_WEIGHT = 0.8 * MAX_WEIGHT
MAX_PACKAGE_WEIGHT = 0.9 * MAX_WEIGHT
MAX_ALLOWED_ITEMS = 1
MAX_ALLOWED_PACKAGES = 1
# TUSMK URL TO SEND NOTIFICATIONS
TUSMK_ON = False

# GET_DATA?Metod=MarketplaceOzon
TUSMK_URL = ""
TUSMK_NEW_ORDER = "GET_DATA?Metod=MarketplaceOzon"
TUSMK_SEND_PDF_LABEL = "GET_DATA?Metod=PostOzonLabel"
TUSMK_SEND_STATUSES = "GET_DATA?Metod=OzonOrderStatus"
TUSMK_SEND_LIST_STATUSES = "GET_DATA?Metod=OzonOrderStatus&return=1"
TUSMK_ISAUTH = False
TUSMK_AUTH = "AUTH_TOKEN"

# STATIC FILES (PDFs) FILES
STATIC_PATH = "connector/pdf/"
STATIC_URL = "http://127.0.0.1/pdf/"

# TELEGRAM CREDENTIALS
TELEGRAM_BOT_TOKEN = "-1"
CHANNEL_ID = -1

# MAIL CREDS AND ADDRESSES
SENDER = "Ozon Notifier <>"

OUTLETS = {
    
}

COMMON_ADDRESSES_PROD = [""]
COMMON_ADDRESSES = [""]

DEBUG = True
