# Generated by Django 4.1.3 on 2023-01-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0002_order_tusmk_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="order_product", to="connector.product"
            ),
        ),
    ]
